/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  text,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', ['sk'])
export const enum_products_currency = pgEnum('enum_products_currency', ['EUR', 'USD', 'GBP'])
export const enum_products_status = pgEnum('enum_products_status', ['draft', 'published'])
export const enum__products_v_version_currency = pgEnum('enum__products_v_version_currency', [
  'EUR',
  'USD',
  'GBP',
])
export const enum__products_v_version_status = pgEnum('enum__products_v_version_status', [
  'draft',
  'published',
])
export const enum__products_v_published_locale = pgEnum('enum__products_v_published_locale', ['sk'])
export const enum_references_status = pgEnum('enum_references_status', ['draft', 'published'])
export const enum__references_v_version_status = pgEnum('enum__references_v_version_status', [
  'draft',
  'published',
])
export const enum__references_v_published_locale = pgEnum('enum__references_v_published_locale', [
  'sk',
])
export const enum_forms_confirmation_type = pgEnum('enum_forms_confirmation_type', [
  'message',
  'redirect',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const products_gallery = pgTable(
  'products_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('products_gallery_order_idx').on(columns._order),
    index('products_gallery_parent_id_idx').on(columns._parentID),
    index('products_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products = pgTable(
  'products',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    category: varchar('category'),
    excerpt: varchar('excerpt'),
    description: jsonb('description'),
    price: numeric('price', { mode: 'number' }),
    currency: enum_products_currency('currency').default('EUR'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    videoUrl: varchar('video_url'),
    specs_dimensions: varchar('specs_dimensions'),
    specs_weight: varchar('specs_weight'),
    specs_power: varchar('specs_power'),
    specs_players: varchar('specs_players'),
    specs_space: varchar('specs_space'),
    specs_notes: varchar('specs_notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_products_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('products_slug_idx').on(columns.slug),
    index('products_image_idx').on(columns.image),
    index('products_updated_at_idx').on(columns.updatedAt),
    index('products_created_at_idx').on(columns.createdAt),
    index('products__status_idx').on(columns._status),
  ],
)

export const _products_v_version_gallery = pgTable(
  '_products_v_version_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_products_v_version_gallery_order_idx').on(columns._order),
    index('_products_v_version_gallery_parent_id_idx').on(columns._parentID),
    index('_products_v_version_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v = pgTable(
  '_products_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => products.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_category: varchar('version_category'),
    version_excerpt: varchar('version_excerpt'),
    version_description: jsonb('version_description'),
    version_price: numeric('version_price', { mode: 'number' }),
    version_currency: enum__products_v_version_currency('version_currency').default('EUR'),
    version_image: integer('version_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_videoUrl: varchar('version_video_url'),
    version_specs_dimensions: varchar('version_specs_dimensions'),
    version_specs_weight: varchar('version_specs_weight'),
    version_specs_power: varchar('version_specs_power'),
    version_specs_players: varchar('version_specs_players'),
    version_specs_space: varchar('version_specs_space'),
    version_specs_notes: varchar('version_specs_notes'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__products_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    snapshot: boolean('snapshot'),
    publishedLocale: enum__products_v_published_locale('published_locale'),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_products_v_parent_idx').on(columns.parent),
    index('_products_v_version_version_slug_idx').on(columns.version_slug),
    index('_products_v_version_version_image_idx').on(columns.version_image),
    index('_products_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_products_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_products_v_version_version__status_idx').on(columns.version__status),
    index('_products_v_created_at_idx').on(columns.createdAt),
    index('_products_v_updated_at_idx').on(columns.updatedAt),
    index('_products_v_snapshot_idx').on(columns.snapshot),
    index('_products_v_published_locale_idx').on(columns.publishedLocale),
    index('_products_v_latest_idx').on(columns.latest),
  ],
)

export const references = pgTable(
  'references',
  {
    id: serial('id').primaryKey(),
    quote: varchar('quote'),
    author: varchar('author'),
    event: varchar('event'),
    photo: integer('photo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_references_status('_status').default('draft'),
  },
  (columns) => [
    index('references_photo_idx').on(columns.photo),
    index('references_updated_at_idx').on(columns.updatedAt),
    index('references_created_at_idx').on(columns.createdAt),
    index('references__status_idx').on(columns._status),
  ],
)

export const _references_v = pgTable(
  '_references_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => references.id, {
      onDelete: 'set null',
    }),
    version_quote: varchar('version_quote'),
    version_author: varchar('version_author'),
    version_event: varchar('version_event'),
    version_photo: integer('version_photo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__references_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    snapshot: boolean('snapshot'),
    publishedLocale: enum__references_v_published_locale('published_locale'),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_references_v_parent_idx').on(columns.parent),
    index('_references_v_version_version_photo_idx').on(columns.version_photo),
    index('_references_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_references_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_references_v_version_version__status_idx').on(columns.version__status),
    index('_references_v_created_at_idx').on(columns.createdAt),
    index('_references_v_updated_at_idx').on(columns.updatedAt),
    index('_references_v_snapshot_idx').on(columns.snapshot),
    index('_references_v_published_locale_idx').on(columns.publishedLocale),
    index('_references_v_latest_idx').on(columns.latest),
  ],
)

export const forms_blocks_checkbox = pgTable(
  'forms_blocks_checkbox',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    width: numeric('width', { mode: 'number' }),
    required: boolean('required'),
    defaultValue: boolean('default_value'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_checkbox_order_idx').on(columns._order),
    index('forms_blocks_checkbox_parent_id_idx').on(columns._parentID),
    index('forms_blocks_checkbox_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_checkbox_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_checkbox_locales = pgTable(
  'forms_blocks_checkbox_locales',
  {
    label: varchar('label'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_blocks_checkbox_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_checkbox.id],
      name: 'forms_blocks_checkbox_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_email = pgTable(
  'forms_blocks_email',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    width: numeric('width', { mode: 'number' }),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_email_order_idx').on(columns._order),
    index('forms_blocks_email_parent_id_idx').on(columns._parentID),
    index('forms_blocks_email_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_email_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_email_locales = pgTable(
  'forms_blocks_email_locales',
  {
    label: varchar('label'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_blocks_email_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_email.id],
      name: 'forms_blocks_email_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_message = pgTable(
  'forms_blocks_message',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_message_order_idx').on(columns._order),
    index('forms_blocks_message_parent_id_idx').on(columns._parentID),
    index('forms_blocks_message_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_message_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_message_locales = pgTable(
  'forms_blocks_message_locales',
  {
    message: jsonb('message'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_blocks_message_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_message.id],
      name: 'forms_blocks_message_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_number = pgTable(
  'forms_blocks_number',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    width: numeric('width', { mode: 'number' }),
    defaultValue: numeric('default_value', { mode: 'number' }),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_number_order_idx').on(columns._order),
    index('forms_blocks_number_parent_id_idx').on(columns._parentID),
    index('forms_blocks_number_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_number_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_number_locales = pgTable(
  'forms_blocks_number_locales',
  {
    label: varchar('label'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_blocks_number_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_number.id],
      name: 'forms_blocks_number_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_select_options = pgTable(
  'forms_blocks_select_options',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    value: varchar('value').notNull(),
  },
  (columns) => [
    index('forms_blocks_select_options_order_idx').on(columns._order),
    index('forms_blocks_select_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_select.id],
      name: 'forms_blocks_select_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_select_options_locales = pgTable(
  'forms_blocks_select_options_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_blocks_select_options_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_select_options.id],
      name: 'forms_blocks_select_options_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_select = pgTable(
  'forms_blocks_select',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    width: numeric('width', { mode: 'number' }),
    placeholder: varchar('placeholder'),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_select_order_idx').on(columns._order),
    index('forms_blocks_select_parent_id_idx').on(columns._parentID),
    index('forms_blocks_select_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_select_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_select_locales = pgTable(
  'forms_blocks_select_locales',
  {
    label: varchar('label'),
    defaultValue: varchar('default_value'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_blocks_select_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_select.id],
      name: 'forms_blocks_select_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_text = pgTable(
  'forms_blocks_text',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    width: numeric('width', { mode: 'number' }),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_text_order_idx').on(columns._order),
    index('forms_blocks_text_parent_id_idx').on(columns._parentID),
    index('forms_blocks_text_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_text_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_text_locales = pgTable(
  'forms_blocks_text_locales',
  {
    label: varchar('label'),
    defaultValue: varchar('default_value'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_blocks_text_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_text.id],
      name: 'forms_blocks_text_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_textarea = pgTable(
  'forms_blocks_textarea',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    width: numeric('width', { mode: 'number' }),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_textarea_order_idx').on(columns._order),
    index('forms_blocks_textarea_parent_id_idx').on(columns._parentID),
    index('forms_blocks_textarea_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_textarea_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_textarea_locales = pgTable(
  'forms_blocks_textarea_locales',
  {
    label: varchar('label'),
    defaultValue: varchar('default_value'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_blocks_textarea_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_textarea.id],
      name: 'forms_blocks_textarea_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_emails = pgTable(
  'forms_emails',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    emailTo: varchar('email_to'),
    cc: varchar('cc'),
    bcc: varchar('bcc'),
    replyTo: varchar('reply_to'),
    emailFrom: varchar('email_from'),
  },
  (columns) => [
    index('forms_emails_order_idx').on(columns._order),
    index('forms_emails_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_emails_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_emails_locales = pgTable(
  'forms_emails_locales',
  {
    subject: varchar('subject').notNull().default("You've received a new message."),
    message: jsonb('message'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_emails_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_emails.id],
      name: 'forms_emails_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms = pgTable(
  'forms',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    confirmationType: enum_forms_confirmation_type('confirmation_type').default('message'),
    redirect_url: varchar('redirect_url'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('forms_updated_at_idx').on(columns.updatedAt),
    index('forms_created_at_idx').on(columns.createdAt),
  ],
)

export const forms_locales = pgTable(
  'forms_locales',
  {
    submitButtonLabel: varchar('submit_button_label'),
    confirmationMessage: jsonb('confirmation_message'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('forms_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const form_submissions_submission_data = pgTable(
  'form_submissions_submission_data',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    field: varchar('field').notNull(),
    value: varchar('value').notNull(),
  },
  (columns) => [
    index('form_submissions_submission_data_order_idx').on(columns._order),
    index('form_submissions_submission_data_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [form_submissions.id],
      name: 'form_submissions_submission_data_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const form_submissions = pgTable(
  'form_submissions',
  {
    id: serial('id').primaryKey(),
    form: integer('form_id')
      .notNull()
      .references(() => forms.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('form_submissions_form_idx').on(columns.form),
    index('form_submissions_updated_at_idx').on(columns.updatedAt),
    index('form_submissions_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    productsID: integer('products_id'),
    referencesID: integer('references_id'),
    formsID: integer('forms_id'),
    'form-submissionsID': integer('form_submissions_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_products_id_idx').on(columns.productsID),
    index('payload_locked_documents_rels_references_id_idx').on(columns.referencesID),
    index('payload_locked_documents_rels_forms_id_idx').on(columns.formsID),
    index('payload_locked_documents_rels_form_submissions_id_idx').on(
      columns['form-submissionsID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['referencesID']],
      foreignColumns: [references.id],
      name: 'payload_locked_documents_rels_references_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['formsID']],
      foreignColumns: [forms.id],
      name: 'payload_locked_documents_rels_forms_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['form-submissionsID']],
      foreignColumns: [form_submissions.id],
      name: 'payload_locked_documents_rels_form_submissions_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const site_settings = pgTable(
  'site_settings',
  {
    id: serial('id').primaryKey(),
    siteName: varchar('site_name'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    phone: varchar('phone'),
    email: varchar('email'),
    address: varchar('address'),
    companyName: varchar('company_name'),
    ico: varchar('ico'),
    facebook: varchar('facebook'),
    instagram: varchar('instagram'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [index('site_settings_logo_idx').on(columns.logo)],
)

export const process_steps = pgTable(
  'process_steps',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    description: varchar('description').notNull(),
  },
  (columns) => [
    index('process_steps_order_idx').on(columns._order),
    index('process_steps_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [process.id],
      name: 'process_steps_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const process = pgTable('process', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_products_gallery = relations(products_gallery, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_gallery._parentID],
    references: [products.id],
    relationName: 'gallery',
  }),
  image: one(media, {
    fields: [products_gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_products = relations(products, ({ one, many }) => ({
  image: one(media, {
    fields: [products.image],
    references: [media.id],
    relationName: 'image',
  }),
  gallery: many(products_gallery, {
    relationName: 'gallery',
  }),
}))
export const relations__products_v_version_gallery = relations(
  _products_v_version_gallery,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_gallery._parentID],
      references: [_products_v.id],
      relationName: 'version_gallery',
    }),
    image: one(media, {
      fields: [_products_v_version_gallery.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations__products_v = relations(_products_v, ({ one, many }) => ({
  parent: one(products, {
    fields: [_products_v.parent],
    references: [products.id],
    relationName: 'parent',
  }),
  version_image: one(media, {
    fields: [_products_v.version_image],
    references: [media.id],
    relationName: 'version_image',
  }),
  version_gallery: many(_products_v_version_gallery, {
    relationName: 'version_gallery',
  }),
}))
export const relations_references = relations(references, ({ one }) => ({
  photo: one(media, {
    fields: [references.photo],
    references: [media.id],
    relationName: 'photo',
  }),
}))
export const relations__references_v = relations(_references_v, ({ one }) => ({
  parent: one(references, {
    fields: [_references_v.parent],
    references: [references.id],
    relationName: 'parent',
  }),
  version_photo: one(media, {
    fields: [_references_v.version_photo],
    references: [media.id],
    relationName: 'version_photo',
  }),
}))
export const relations_forms_blocks_checkbox_locales = relations(
  forms_blocks_checkbox_locales,
  ({ one }) => ({
    _parentID: one(forms_blocks_checkbox, {
      fields: [forms_blocks_checkbox_locales._parentID],
      references: [forms_blocks_checkbox.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_checkbox = relations(
  forms_blocks_checkbox,
  ({ one, many }) => ({
    _parentID: one(forms, {
      fields: [forms_blocks_checkbox._parentID],
      references: [forms.id],
      relationName: '_blocks_checkbox',
    }),
    _locales: many(forms_blocks_checkbox_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_email_locales = relations(
  forms_blocks_email_locales,
  ({ one }) => ({
    _parentID: one(forms_blocks_email, {
      fields: [forms_blocks_email_locales._parentID],
      references: [forms_blocks_email.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_email = relations(forms_blocks_email, ({ one, many }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_email._parentID],
    references: [forms.id],
    relationName: '_blocks_email',
  }),
  _locales: many(forms_blocks_email_locales, {
    relationName: '_locales',
  }),
}))
export const relations_forms_blocks_message_locales = relations(
  forms_blocks_message_locales,
  ({ one }) => ({
    _parentID: one(forms_blocks_message, {
      fields: [forms_blocks_message_locales._parentID],
      references: [forms_blocks_message.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_message = relations(forms_blocks_message, ({ one, many }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_message._parentID],
    references: [forms.id],
    relationName: '_blocks_message',
  }),
  _locales: many(forms_blocks_message_locales, {
    relationName: '_locales',
  }),
}))
export const relations_forms_blocks_number_locales = relations(
  forms_blocks_number_locales,
  ({ one }) => ({
    _parentID: one(forms_blocks_number, {
      fields: [forms_blocks_number_locales._parentID],
      references: [forms_blocks_number.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_number = relations(forms_blocks_number, ({ one, many }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_number._parentID],
    references: [forms.id],
    relationName: '_blocks_number',
  }),
  _locales: many(forms_blocks_number_locales, {
    relationName: '_locales',
  }),
}))
export const relations_forms_blocks_select_options_locales = relations(
  forms_blocks_select_options_locales,
  ({ one }) => ({
    _parentID: one(forms_blocks_select_options, {
      fields: [forms_blocks_select_options_locales._parentID],
      references: [forms_blocks_select_options.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_select_options = relations(
  forms_blocks_select_options,
  ({ one, many }) => ({
    _parentID: one(forms_blocks_select, {
      fields: [forms_blocks_select_options._parentID],
      references: [forms_blocks_select.id],
      relationName: 'options',
    }),
    _locales: many(forms_blocks_select_options_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_select_locales = relations(
  forms_blocks_select_locales,
  ({ one }) => ({
    _parentID: one(forms_blocks_select, {
      fields: [forms_blocks_select_locales._parentID],
      references: [forms_blocks_select.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_select = relations(forms_blocks_select, ({ one, many }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_select._parentID],
    references: [forms.id],
    relationName: '_blocks_select',
  }),
  _locales: many(forms_blocks_select_locales, {
    relationName: '_locales',
  }),
  options: many(forms_blocks_select_options, {
    relationName: 'options',
  }),
}))
export const relations_forms_blocks_text_locales = relations(
  forms_blocks_text_locales,
  ({ one }) => ({
    _parentID: one(forms_blocks_text, {
      fields: [forms_blocks_text_locales._parentID],
      references: [forms_blocks_text.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_text = relations(forms_blocks_text, ({ one, many }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_text._parentID],
    references: [forms.id],
    relationName: '_blocks_text',
  }),
  _locales: many(forms_blocks_text_locales, {
    relationName: '_locales',
  }),
}))
export const relations_forms_blocks_textarea_locales = relations(
  forms_blocks_textarea_locales,
  ({ one }) => ({
    _parentID: one(forms_blocks_textarea, {
      fields: [forms_blocks_textarea_locales._parentID],
      references: [forms_blocks_textarea.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_blocks_textarea = relations(
  forms_blocks_textarea,
  ({ one, many }) => ({
    _parentID: one(forms, {
      fields: [forms_blocks_textarea._parentID],
      references: [forms.id],
      relationName: '_blocks_textarea',
    }),
    _locales: many(forms_blocks_textarea_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_forms_emails_locales = relations(forms_emails_locales, ({ one }) => ({
  _parentID: one(forms_emails, {
    fields: [forms_emails_locales._parentID],
    references: [forms_emails.id],
    relationName: '_locales',
  }),
}))
export const relations_forms_emails = relations(forms_emails, ({ one, many }) => ({
  _parentID: one(forms, {
    fields: [forms_emails._parentID],
    references: [forms.id],
    relationName: 'emails',
  }),
  _locales: many(forms_emails_locales, {
    relationName: '_locales',
  }),
}))
export const relations_forms_locales = relations(forms_locales, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_locales._parentID],
    references: [forms.id],
    relationName: '_locales',
  }),
}))
export const relations_forms = relations(forms, ({ many }) => ({
  _blocks_checkbox: many(forms_blocks_checkbox, {
    relationName: '_blocks_checkbox',
  }),
  _blocks_email: many(forms_blocks_email, {
    relationName: '_blocks_email',
  }),
  _blocks_message: many(forms_blocks_message, {
    relationName: '_blocks_message',
  }),
  _blocks_number: many(forms_blocks_number, {
    relationName: '_blocks_number',
  }),
  _blocks_select: many(forms_blocks_select, {
    relationName: '_blocks_select',
  }),
  _blocks_text: many(forms_blocks_text, {
    relationName: '_blocks_text',
  }),
  _blocks_textarea: many(forms_blocks_textarea, {
    relationName: '_blocks_textarea',
  }),
  emails: many(forms_emails, {
    relationName: 'emails',
  }),
  _locales: many(forms_locales, {
    relationName: '_locales',
  }),
}))
export const relations_form_submissions_submission_data = relations(
  form_submissions_submission_data,
  ({ one }) => ({
    _parentID: one(form_submissions, {
      fields: [form_submissions_submission_data._parentID],
      references: [form_submissions.id],
      relationName: 'submissionData',
    }),
  }),
)
export const relations_form_submissions = relations(form_submissions, ({ one, many }) => ({
  form: one(forms, {
    fields: [form_submissions.form],
    references: [forms.id],
    relationName: 'form',
  }),
  submissionData: many(form_submissions_submission_data, {
    relationName: 'submissionData',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
    referencesID: one(references, {
      fields: [payload_locked_documents_rels.referencesID],
      references: [references.id],
      relationName: 'references',
    }),
    formsID: one(forms, {
      fields: [payload_locked_documents_rels.formsID],
      references: [forms.id],
      relationName: 'forms',
    }),
    'form-submissionsID': one(form_submissions, {
      fields: [payload_locked_documents_rels['form-submissionsID']],
      references: [form_submissions.id],
      relationName: 'form-submissions',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_site_settings = relations(site_settings, ({ one }) => ({
  logo: one(media, {
    fields: [site_settings.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations_process_steps = relations(process_steps, ({ one }) => ({
  _parentID: one(process, {
    fields: [process_steps._parentID],
    references: [process.id],
    relationName: 'steps',
  }),
}))
export const relations_process = relations(process, ({ many }) => ({
  steps: many(process_steps, {
    relationName: 'steps',
  }),
}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_products_currency: typeof enum_products_currency
  enum_products_status: typeof enum_products_status
  enum__products_v_version_currency: typeof enum__products_v_version_currency
  enum__products_v_version_status: typeof enum__products_v_version_status
  enum__products_v_published_locale: typeof enum__products_v_published_locale
  enum_references_status: typeof enum_references_status
  enum__references_v_version_status: typeof enum__references_v_version_status
  enum__references_v_published_locale: typeof enum__references_v_published_locale
  enum_forms_confirmation_type: typeof enum_forms_confirmation_type
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  products_gallery: typeof products_gallery
  products: typeof products
  _products_v_version_gallery: typeof _products_v_version_gallery
  _products_v: typeof _products_v
  references: typeof references
  _references_v: typeof _references_v
  forms_blocks_checkbox: typeof forms_blocks_checkbox
  forms_blocks_checkbox_locales: typeof forms_blocks_checkbox_locales
  forms_blocks_email: typeof forms_blocks_email
  forms_blocks_email_locales: typeof forms_blocks_email_locales
  forms_blocks_message: typeof forms_blocks_message
  forms_blocks_message_locales: typeof forms_blocks_message_locales
  forms_blocks_number: typeof forms_blocks_number
  forms_blocks_number_locales: typeof forms_blocks_number_locales
  forms_blocks_select_options: typeof forms_blocks_select_options
  forms_blocks_select_options_locales: typeof forms_blocks_select_options_locales
  forms_blocks_select: typeof forms_blocks_select
  forms_blocks_select_locales: typeof forms_blocks_select_locales
  forms_blocks_text: typeof forms_blocks_text
  forms_blocks_text_locales: typeof forms_blocks_text_locales
  forms_blocks_textarea: typeof forms_blocks_textarea
  forms_blocks_textarea_locales: typeof forms_blocks_textarea_locales
  forms_emails: typeof forms_emails
  forms_emails_locales: typeof forms_emails_locales
  forms: typeof forms
  forms_locales: typeof forms_locales
  form_submissions_submission_data: typeof form_submissions_submission_data
  form_submissions: typeof form_submissions
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  site_settings: typeof site_settings
  process_steps: typeof process_steps
  process: typeof process
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_products_gallery: typeof relations_products_gallery
  relations_products: typeof relations_products
  relations__products_v_version_gallery: typeof relations__products_v_version_gallery
  relations__products_v: typeof relations__products_v
  relations_references: typeof relations_references
  relations__references_v: typeof relations__references_v
  relations_forms_blocks_checkbox_locales: typeof relations_forms_blocks_checkbox_locales
  relations_forms_blocks_checkbox: typeof relations_forms_blocks_checkbox
  relations_forms_blocks_email_locales: typeof relations_forms_blocks_email_locales
  relations_forms_blocks_email: typeof relations_forms_blocks_email
  relations_forms_blocks_message_locales: typeof relations_forms_blocks_message_locales
  relations_forms_blocks_message: typeof relations_forms_blocks_message
  relations_forms_blocks_number_locales: typeof relations_forms_blocks_number_locales
  relations_forms_blocks_number: typeof relations_forms_blocks_number
  relations_forms_blocks_select_options_locales: typeof relations_forms_blocks_select_options_locales
  relations_forms_blocks_select_options: typeof relations_forms_blocks_select_options
  relations_forms_blocks_select_locales: typeof relations_forms_blocks_select_locales
  relations_forms_blocks_select: typeof relations_forms_blocks_select
  relations_forms_blocks_text_locales: typeof relations_forms_blocks_text_locales
  relations_forms_blocks_text: typeof relations_forms_blocks_text
  relations_forms_blocks_textarea_locales: typeof relations_forms_blocks_textarea_locales
  relations_forms_blocks_textarea: typeof relations_forms_blocks_textarea
  relations_forms_emails_locales: typeof relations_forms_emails_locales
  relations_forms_emails: typeof relations_forms_emails
  relations_forms_locales: typeof relations_forms_locales
  relations_forms: typeof relations_forms
  relations_form_submissions_submission_data: typeof relations_form_submissions_submission_data
  relations_form_submissions: typeof relations_form_submissions
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_site_settings: typeof relations_site_settings
  relations_process_steps: typeof relations_process_steps
  relations_process: typeof relations_process
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
